#!/bin/bash
# set -e

# git submodule update --init --recursive
./build-third-party.sh
(cd examples/gstreamer
 (cat index_html.h.template;sed -e 's/$/ \\n\\/' -e 's/"/\\"/g' <index.html
  echo '";'; echo \#endif // GSTREAMER_INDEX_HTML_H_) >index_html.h
 )
if [ ! -d cmake ]; then mkdir cmake; fi
export LDFLAGS="-Wl,--copy-dt-needed-entries"
(cd cmake
cmake -DCMAKE_BUILD_TYPE=Release ..
cd examples
cmake -DENABLE_EXAMPLES=on -DCMAKE_BUILD_TYPE=Release ..
make)
cp cmake/examples/gstreamer/gstreamer .
