#!/bin/bash

# git clone --recursive https://github.com/sepfy/pear
git submodule update --init --recursive
sudo apt -y install libglib2.0-dev libssl-dev git cmake ninja-build
sudo apt install libsrtp2-dev libgtk-3-dev
sudo pip3 install meson
./gob
