#!/bin/bash
# set -e

#    LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libasan.so.4 \


env PIPE_LINE='v4l2src ! videorate ! video/x-raw,width=1280,height=720,framerate=30/1 ! videoconvert ! queue ! x264enc bitrate=3000 speed-preset=ultrafast tune=zerolatency key-int-max=30 ! video/x-h264,profile=constrained-baseline ! queue ! h264parse ! queue ! rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1500 ! appsink name=pear-sink' \
    ./gstreamer

exit 0

env \
    GST_DEBUG=*:3 \
    PIPE_LINE='v4l2src num-buffers=4000 ! videorate ! video/x-raw,width=1280,height=720,framerate=30/1 ! queue ! videoconvert ! queue ! x264enc bitrate=3000 b-adapt=true rc-lookahead=6 speed-preset=ultrafast tune=zerolatency key-int-max=20 pass=quant ! queue ! video/x-h264,profile=constrained-baseline ! queue ! h264parse ! queue ! rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1500 ! appsink name=pear-sink' \
    ./gstreamer

exit 0
env PIPE_LINE='gst-launch-1.0 -vvv -e mp4mux name=filemux ! v4l2src device=/dev/video0 do-timestamp=true ! video/x-h264, width=1920, height=1080, framerate=30/1 ! tee name=tsplit ! queue !h264parse ! \
rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1400 ! appsink name=pear-sink !
filemux.video_0 pulsesrc device=alsa_input.usb-Magic_Control_Technology_Corp._j5create_360_Meeting_Webcam_V1.00.28-02.analog-stereo do-timestamp=true ! audio/x-raw ! queue ! audioconvert ! voaacenc ! filemux.audio_0' ./gstreamer

exit 0

gst-launch-1.0 -vvv -e mp4mux name=filemux ! v4l2src device=/dev/video0 do-timestamp=true ! video/x-h264, width=1920, height=1080, framerate=30/1 ! tee name=tsplit ! queue ! h264parse ! omxh264dec ! videoconvert ! videoscale ! video/x-raw, width=1280, height=720 ! xvimagesink sync=false tsplit. ! queue ! h264parse ! filemux.video_0 pulsesrc device=alsa_input.usb-Magic_Control_Technology_Corp._j5create_360_Meeting_Webcam_V1.00.28-02.analog-stereo do-timestamp=true ! audio/x-raw ! queue ! audioconvert ! voaacenc ! filemux.audio_0
