#!/bin/bash
# set -e

git submodule update --init --recursive
./build-third-party.sh
(cd examples/gstreamer
 (cat index_html.h.template;sed -e 's/$/ \\n\\/' -e 's/"/\\"/g' <index.html
  echo '";'; echo \#endif // GSTREAMER_INDEX_HTML_H_) >index_html.h
 )
if [ ! -d cmake ]; then mkdir cmake; fi
(cd cmake
cmake -DCMAKE_BUILD_TYPE=Debug ..
cd examples
cmake -DENABLE_EXAMPLES=on -DCMAKE_BUILD_TYPE=Debug ..
make)
cp cmake/examples/gstreamer/gstreamer .

echo Modify this comnand line as needed for source, resolution.  Connect w/ web browser.  Right now, experiencing several second delay on connection, which needs debugging.

./gstreamer
