#!/bin/bash
# set -e


# echo Modify this comnand line as needed for source, resolution.  Connect w/ web browser.  Right now, experiencing several second delay on connection, which needs debugging.

env PIPE_LINE='v4l2src ! videorate ! video/x-raw,width=2560,height=720,framerate=60/1 ! videoconvert ! queue ! x264enc bitrate=3000 speed-preset=ultrafast tune=zerolatency key-int-max=30 ! video/x-h264,profile=constrained-baseline ! queue ! h264parse ! queue ! rtph264pay config-interval=-1 pt=102 seqnum-offset=0 timestamp-offset=0 mtu=1400 ! appsink name=pear-sink' ./gstreamer
