#!/bin/bash
# set -e


# echo Modify this comnand line as needed for source, resolution.  Connect w/ web browser.  Right now, experiencing several second delay on connection, which needs debugging.
# HW264 in from camera:
env PIPE_LINE='v4l2src num-buffers=4000 ! videorate ! video/x-h264,width=2560,height=720,framerate=60/1 ! h264parse ! rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1500 ! queue ! appsink name=pear-sink' ./gstreamer

exit 0

#Good:
env PIPE_LINE='v4l2src num-buffers=4000 ! videorate ! video/x-raw,width=2560,height=720,framerate=60/1 ! videoconvert ! queue ! x264enc bitrate=3000 b-adapt=true rc-lookahead=6 speed-preset=ultrafast tune=zerolatency key-int-max=20 pass=quant ! queue !  video/x-h264,profile=constrained-baseline ! queue ! h264parse ! queue ! rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1500 ! appsink name=pear-sink' ./gstreamer

exit 0

# Works solidly, without lockup

env PIPE_LINE='v4l2src ! videorate ! video/x-raw,width=2560,height=720,framerate=60/1 ! videoconvert ! queue ! x264enc bitrate=3000 speed-preset=ultrafast tune=zerolatency key-int-max=30 ! video/x-h264,profile=constrained-baseline ! queue ! h264parse ! queue ! rtph264pay config-interval=-1 pt=100 seqnum-offset=0 timestamp-offset=0 mtu=1500 ! appsink name=pear-sink' ./gstreamer
